name: basic-model-tests-daily
on:
  workflow_dispatch:
  schedule:
    - cron:  '48 19 * * *'
env:
  HF_TOKEN: ${{ secrets.HUGGING_FACE_HUB_TOKEN }}
  HF_DATASETS_CACHE: /nvme0/huggingface_hub
  HF_HUB_CACHE: /nvme0/huggingface_hub
  ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
  PYTORCH_CUDA_ALLOC_CONF: expandable_segments:True

jobs:
  HF_model_S1:
    runs-on: [linux-a100]
    strategy:
      matrix:
        transformers-version: [4.53.0, 4.55.3]
    container:
      image: openmmlab/lmdeploy:latest-cu12.8
      options: "--gpus=all --ipc=host --user root -e PIP_CACHE_DIR=/root/.cache/pip -e NVIDIA_DISABLE_REQUIRE=1 --pull never"
      volumes:
        - /nvme0/github-actions/pip-cache:/root/.cache/pip
        - /nvme0/huggingface_hub:/nvme0/huggingface_hub
        - /usr/share/zoneinfo/Asia/Shanghai:/etc/localtime:ro
    steps:
    - uses: actions/checkout@v3
    - name: load_hf_model
      if: matrix.transformers-version != 'latest'
      run: |
        pip install transformers==${{ matrix.transformers-version }} --force-reinstall
    - name: load_latest_hf_model
      if: matrix.transformers-version == 'latest'
      run: |
        pip install transformers --force-reinstall
    - name: check env
      run: |
        pip list
        lmdeploy check_env
    - name: run_test
      run: |
        pip install pytest pytest-xdist decord
        pytest tests/test_hf_transformers.py -n 1


  notify_to_feishu:
    if: ${{ always() && !cancelled() && contains(needs.*.result, 'failure') && (github.ref_name == 'develop' || github.ref_name == 'main') }}
    needs: [HF_model_S1]
    runs-on: [linux-a100]
    steps:
    - name: mask env
      run: |
        echo "::add-mask::${{env.WORKSPACE_PREFIX}}"
        echo "::add-mask::$path_prefix"
    - name: notify
      run: |
        curl -X POST -H "Content-Type: application/json" -d '{"msg_type":"post","content":{"post":{"zh_cn":{"title":"Internlm GitHubAction Failed","content":[[{"tag":"text","text":""},{"tag":"a","text":"Please click here for details ","href":"https://github.com/'${{ github.repository }}'/actions/runs/'${GITHUB_RUN_ID}'"},{"tag":"at","user_id":"'${{ secrets.USER_ID }}'"}]]}}}}'  ${{ secrets.WEBHOOK_URL }}
